# Makefile для Задание 3
CC = g++
CFLAGS = -std=c++17 -Wall -Wextra
TARGET = test_Time_with_counters

all: $(TARGET)

$(TARGET):
	$(CC) $(CFLAGS) main.cpp Time.cpp -o $(TARGET)

clean:
	rm -f $(TARGET)

